name: version test and push image
on: [push,workflow_dispatch]

jobs:
  version-test:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [windows-latest,ubuntu-latest]
         node_version: [14,15]
    steps:
       - name: checkout the code
         uses: actions/checkout@v3
       - name: download node
         uses: actions/setup-node@v3
         with:
           node_version: ${{ matrix.node_version }}
       - name: print the reult
         run: node -v
  docker-build-upload:
    runs-on: ubuntu-latest
    steps:
       - name: checkout the code
         uses: actions/checkout@v3
       - name: login into docker
         uses: docker/login-action@v3
         with:
           username: $ {{ secrets.DOCKER_USERNAME }}
           password: $ {{ secrets.DOCKER_PASSWORD }}
       - name: setup buildx
         uses: docker/setup-buildx-action@v3
       - name: build and push
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/repo:latest
         
